// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw3XNDzKHumfFjsXE5Rs6qFAwzRgMIL6Q',
    appId: '1:681147882409:web:55e02867f2737cbfc2c2b8',
    messagingSenderId: '681147882409',
    projectId: 'smart-harvest-1fb37',
    authDomain: 'smart-harvest-1fb37.firebaseapp.com',
    storageBucket: 'smart-harvest-1fb37.firebasestorage.app',
    measurementId: 'G-G6MWGQR9EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAAnCkLqF1INkNjYgop44EG2KJgyWBCHM',
    appId: '1:681147882409:android:c3f9476ed4e4e7dbc2c2b8',
    messagingSenderId: '681147882409',
    projectId: 'smart-harvest-1fb37',
    storageBucket: 'smart-harvest-1fb37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2rGTX_vqYo-K9g8F0x9aBvuDEXW2h_To',
    appId: '1:681147882409:ios:56193e1356a73f61c2c2b8',
    messagingSenderId: '681147882409',
    projectId: 'smart-harvest-1fb37',
    storageBucket: 'smart-harvest-1fb37.firebasestorage.app',
    androidClientId: '681147882409-85i25imknaivo09np4mv88u0m4tdpeb5.apps.googleusercontent.com',
    iosClientId: '681147882409-k7j6evrjl0en9hc1ne5lld9c4arkpu5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHarvest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2rGTX_vqYo-K9g8F0x9aBvuDEXW2h_To',
    appId: '1:681147882409:ios:56193e1356a73f61c2c2b8',
    messagingSenderId: '681147882409',
    projectId: 'smart-harvest-1fb37',
    storageBucket: 'smart-harvest-1fb37.firebasestorage.app',
    androidClientId: '681147882409-85i25imknaivo09np4mv88u0m4tdpeb5.apps.googleusercontent.com',
    iosClientId: '681147882409-k7j6evrjl0en9hc1ne5lld9c4arkpu5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHarvest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw3XNDzKHumfFjsXE5Rs6qFAwzRgMIL6Q',
    appId: '1:681147882409:web:209b195d4f70f9b5c2c2b8',
    messagingSenderId: '681147882409',
    projectId: 'smart-harvest-1fb37',
    authDomain: 'smart-harvest-1fb37.firebaseapp.com',
    storageBucket: 'smart-harvest-1fb37.firebasestorage.app',
    measurementId: 'G-C92VK2C2JD',
  );
}
